### ISSUE TITLE
unable conclude the task.

### ISSUE THREAD

**Issue by dennishuang85** [FoundationAgents/OpenManus#53]
After all the process done, it cann't conclude all the research. if enter “exit", there is a "ValueError: I/O operation on closed pipe". 

![Image](https://github.com/user-attachments/assets/020fa88e-389b-4beb-83ea-23b880c27a7f)

**Comment by Abel-csd** [comment]
I've fixed this issue by installing the playwright.

**Comment by tapistefan** [comment]
> I've fixed this issue by installing the playwright.

I have playwright properly installed and this doesn't fix the error. I think error is related to ProactorEventLoop oon windows.
This gent proposed a fix https://github.com/mannaandpoem/OpenManus/pull/631 But for me his fix breaks other things and rises other errors.

**Comment by akaisempai** [comment]
Has anyone solved this problem? Playwright is installed. But it's still a mistake at the very end.

**Comment by kingafy** [comment]
Me facing similar issue .Playwright is installed but get this error all the time post completion of the task
